### PR TITLE
443 - Fix Transfer-Encoding: chunked for downloads

### PR DESCRIPTION
**Pull request by th317erd**
PR for issue #443

This may not be the best fix... open to suggestions for a better fix.

### CODE REVIEW

**Comment by ryam4u** [comment]
This fixes the bug, please merge it

**Comment by sonudoo** [comment]
Yes. This does fix the regression. But it is a bit of  hacky way to do it. Can you please add a comment for the if statement before it gets merged?

**Comment by Traviskn** [comment]
I reverted #396 which introduced the regression, I am curious if there is any way to know the expected content length when using chunked transfer encoding?

**Comment by sonudoo** [comment]
In that case, we have to check for a End marker which can be an empty body or EOL. I have to check what exactly we get in response. We can introduce another variable that keeps track of this End marker and return true is it was received.

**Comment by th317erd** [comment]
Yeah, I can add a comment, but it sounds like more is needed (and it also sounds like I may not be the best person to do such work). Would you still like me to fix this and have it merged (since you reverted the other "fix")? What would you like to do with this PR?

**Comment by Traviskn** [comment]
I think we will need a new pull request implementing the strategy described by @sonudoo

**Comment by sonudoo** [comment]
I will be raising one in the next week implementing that strategy.

**Comment by sonudoo** [comment]
Here is my attempt. Have a look at this PR: https://github.com/joltup/rn-fetch-blob/pull/449
@Traviskn @th317erd

**Pull request closed without merging**
