### PR TITLE
convert to new react native config format

### PR DESCRIPTION
**Pull request by Traviskn**

### CODE REVIEW

**Comment by Traviskn** [comment]
according to the [react-native cli docs](https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide): `hooks are considered anti-pattern, please avoid them`
I'm not sure that we should continue to support the prelink script that auto-adds the android manifest permissions. it would likely be best to just document the required permissions and require that you add them yourself

**Comment by IntelliJAbhishek** [comment]
@Traviskn  Just add required permission in docs. No need to autolink permission. A proper docs would be enough.

**Comment by oleksandr-dziuban** [comment]
@IntelliJAbhishek Hello, can we merge this PR?

**Comment by IntelliJAbhishek** [comment]
@oleksandr-dziuban maintainers of this repo can merge this or..

**Comment by filmhomage** [comment]
Same here.  Please merge this PR.

**Comment by congnguyen91** [comment]
+1 please check this PR & merge :) thanks

**Comment by caigehui** [comment]
+1 please check this PR & merge :) thanks

**Comment by caigehui** [comment]
+1 please check this PR & merge :) thanks

**Comment by BaderSerhan** [comment]
Waiting for this merge ! :)

**Comment by mvanroon** [comment]
>it would likely be best to just document the required permissions and require that you add them yourself

looks like this is currently the case, I think we safely remove the prelink.js (and the hook) altogether now

**Comment by romreed** [comment]
When this merge will be in master???

**Comment by romreed** [comment]
When this merge will be in master?

**Comment by mvanroon** [comment]
> When this merge will be in master?

When someone merges the PR?

**Comment by oleksandr-dziuban** [comment]
@mvanroon Hello, is it possible to merge this PR? Or this library is not maintained anymore?

**Comment by oleksandr-dziuban** [comment]
> I don't think we need the react-native.config.js script at all.
> The script installs permissions, but these are already mentioned in the readme

We need it anyway to mograte to latest react-native standards, so could you please merge it?

**Comment by Traviskn** [comment]
merging for now, planning on a follow up PR to update the README and remove the hook entirely

**Pull request merged**
