### PR TITLE
Fix issue 230 by removing provider tag

### PR DESCRIPTION
**Pull request by shtefanilie**
Removed provider tag in the `AndroidManifest` file as it is causing the errors.

### CODE REVIEW

**Comment by shtefanilie** [comment]
Issue 230 can be found [here] (https://github.com/joltup/rn-fetch-blob/issues/230)

**Comment by maxkomarychev** [comment]
Hey @shtefanilie, these lines were added to solve other issue some time ago: https://github.com/joltup/rn-fetch-blob/pull/58 are you 100% there will be no implications?
There's a code that expects provider to exist. Perhaps the README should be updated in the similar way as in react-native-share project: https://github.com/react-native-community/react-native-share/blob/03183deb41617a4d145b42bffbea4ca39df0a165/README.md#android-install (step 5)

**Comment by maxkomarychev** [comment]
@Auugustocesar can you suggest something?

**Comment by shtefanilie** [comment]
Hey @maxkomarychev, I am not using `react-native-share` but instead I am using [react-native-smooch](https://github.com/smooch/react-native-smooch). 
After adding and linking it to the project, I get this error.

```
/Project/android/app/src/main/AndroidManifest.xml:45:13-72 Error:
        Attribute provider#android.support.v4.content.FileProvider@authorities value=(com.project.SMOOCH_FILE_PROVIDER) from [io.smooch:ui:5.14.5] AndroidManifest.xml:45:13-72
        is also present at [:rn-fetch-blob] AndroidManifest.xml:38:13-60 value=(com.project.provider).
        Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:43:9-51:20 to override.
``` 

After I delete the `<provider>` it compiles and all works as it should. 
I tried doing what you suggested [here](https://github.com/joltup/rn-fetch-blob/pull/250#issuecomment-443114682), but with no avail.

I continued digging and I found that in the `io.smooch.ui` [.pom file](https://github.com/smooch/smooch-android/blob/master/ui/ui-5.14.5.pom) there is a reference for this `v4 support` component. Any suggestions on what should I do?

I will open an issue on [smooch-android](https://github.com/smooch/smooch-android).

**Comment by shtefanilie** [comment]
Closing this pull request as I managed to fix the issue by adding a `<provider>` tag inside my main `AppManifest` file, and creating a fileprovider path file.

```
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"
                tools:replace="android:resource"/>
        </provider>
```

**Pull request closed without merging**
