### PR TITLE
Fix compatibility with 0.69.0

### PR DESCRIPTION
**Pull request by RnbWd**
The latest version of react-native does not support react-native.config.js, so it does not bundle rn-fetch-blob anymore. This PR removes the pre-link scripts, and adds more documentation in the readme for a manual fix.

### CODE REVIEW

**Comment by msotnikov** [comment]
It brokes the compability with older versions. Dependencies is a HUGE problem all react-native ecosystem. post-install script with checking version will better here.

**Comment by micahlt** [comment]
@rpenfold can we _please_ get this merged?  Without it the library is completely useless.

**Comment by fosztomatyas** [comment]
We are also blocked by this. Any updates for when we could have this merged?

**Review by rpenfold — APPROVED** [review]

**Comment by rpenfold** [comment]
@RnbWd thanks for addressing this! PR looks good and I have merged your branch. I'll work on getting a release out within the week.

**Comment by rpenfold** [comment]
I've published a `0.13.0-beta.2` version to beta with this fix to NPM. After a bit more testing I intend to also publish this change to a `0.12.1` version as well.

**Comment by ricardobeat** [comment]
@rpenfold any chance we'll get that release soon?

**Pull request merged**
