### PR TITLE
Fixing #236 which did not expect null from DownloadManager.query()

### PR DESCRIPTION
**Pull request by mark-plukkido**
Please note: I wasn't able to find contribution guidelines for PRs, so PR is against master as the issue-236 branch is quite stale.

This is a proposed fix to issue #236 which was due to a missing null check in onReceive() where DownloadManager.query() can return null, resulting in NullPointerException in some rare cases.

### CODE REVIEW

**Comment by mark-plukkido** [comment]
Code was deployed in a live application. I tried to update the test cases and run those, but it seemed like a longer effort and had to abandon it.

**Comment by Dimon70007** [comment]
Oh. There is no tests in this library. 
@Traviskn Could you approve this PR ?

**Comment by Dimon70007** [comment]
oh no. https://github.com/joltup/rn-fetch-blob/issues/236 - is because of downloading large files. this fix did not helped me.

**Comment by Traviskn** [comment]
If this is working in a live application I am comfortable with merging, thanks for your PR!

**Pull request merged**
