### PR TITLE
When Ios upload image should delete charset=utf-8 in http request header content-type ,otherwise will cause bug

### PR DESCRIPTION
**Pull request by Tim-Burbank**
Thank you for making a pull request ! Just a gentle reminder :)

1. If the PR is offering a feature please make the request to our "Feature Branch" 0.11.0
2. Bug fix request to "Bug Fix Branch" 0.10.9
3. Correct README.md can directly to master

### CODE REVIEW

**Comment by Tim-Burbank** [comment]
fix ios upload bugs

**Comment by Tim-Burbank** [comment]
fix ios upload image bug

**Comment by Traviskn** [comment]
Can you describe more about the bug that is caused by charset=utf-8 in the request header?  How can we reproduce the bug? We have been uploading files from iOS without problems for some time.

**Comment by Tim-Burbank** [comment]
When i upload image to aliyun oss use 'Content-Type': 'multipart/form-data' ,  will cause a bug , they are not accept this header when upload image

**Comment by okb1100** [comment]
We also have the same problem. 
Our server returns a response with status code 403 when `Content-Type` has `charset=utf-8` along with `multipart/form-data`, no problems with Android since `charset=utf-8` is appended only on iOS.
Also the error is not limited to image files, we are trying to upload text/plain files. Appending `charset=utf-8` to `Content-Type` only on iOS is inconsistent and should be removed.

react-native version: 0.56
rn-fetch-blob version: 0.10.12

**Comment by mokai** [comment]
Similarly, because `charset=utf-8` is added, 405 Status is returned when uploading images to Alibaba Cloud OSS.

react-native version: 0.59.5
rn-fetch-blob version: 0.10.15

**Comment by Traviskn** [comment]
`charset=urf-8` has been removed by #310

**Pull request closed without merging**
