### PR TITLE
fixes [joltup/rn-fetch-blob#225]

### PR DESCRIPTION
**Pull request by mgeier63**
Fixes [joltup/rn-fetch-blob#225]

### CODE REVIEW

**Comment by rajivshah3** [comment]
@mgeier63 should `master` be the target branch for this PR?

**Comment by mgeier63** [comment]
@rajivshah3 according to these instructions [https://github.com/joltup/rn-fetch-blob-dev/blob/master/README.md](https://github.com/joltup/rn-fetch-blob-dev/blob/master/README.md) the current "bug fix branch" is `v0.10.9` - so I chose that one as the target branch.

**Comment by rajivshah3** [comment]
Oh whoops, didn't see that. Don't mind me then 😄

**Comment by Traviskn** [comment]
sorry https://github.com/joltup/rn-fetch-blob-dev/blob/master/README.md has not been updated, we are no longer using the v0.10.9 - all PRs from now on should be opened against the master branch

**Comment by demarchisd** [comment]
any idea when this will be merged into master?

**Comment by jaisonveneri** [comment]
Any prevision to merge with master?

**Comment by jsamr** [comment]
Please merge ; I've just faced this issue today.

**Comment by mo-patel** [comment]
Any clue when this will be merged?

**Comment by Traviskn** [comment]
thanks for this PR, apologies for the delayed review

**Comment by tmaly1980** [comment]
@Traviskn Why is this going into 0.10.9? And not master?

**Comment by Traviskn** [comment]
Oh I didn't realize that this PR wasn't opened against the master branch 🤦‍♂

**Comment by tmaly1980** [comment]
@Traviskn So what needs to happen for this bugfix to go out? This is breaking all my Android O/P apps.

**Comment by tmaly1980** [comment]
@Traviskn Looks like this is already on master:

https://github.com/joltup/rn-fetch-blob/commit/95207a99bcb86d07f634450a1cb5a000345c8f13

**Pull request merged**
