### PR TITLE
Require cycle refactor fix

### PR DESCRIPTION
**Pull request by sbaiahmed1**

### CODE REVIEW

**Comment by arthwood** [comment]
#688 already addresses this.

**Comment by sbaiahmed1** [comment]
Yes you have to merge one of em...

**Comment by arthwood** [comment]
> Yes you have to merge one of em...

@sbaiahmed1 - sorry, my point was the PR already exists, so no reason to create another one. Instead, this one can be closed and any comments should go to #688.
P.S. I'm not the maintainer.

**Comment by rpenfold** [comment]
PR #688 has been merged. Closing this PR since it duplicates that change. We appreciate everyone that participated on this PR. Thank you!

**Pull request closed without merging**
