### PR TITLE
Android security expose

### PR DESCRIPTION
**Pull request by Moreno97**
Coming from https://github.com/wkh237/react-native-fetch-blob/pull/614
It solves the exposed security exception on Android devices with API version >= 24. In older API's the code hasn't changed, still uses file://....

### CODE REVIEW

**Comment by Bartlomiejsz** [comment]
Is there a chance it will be merged soon?

**Comment by Traviskn** [comment]
I need to check, but I think we had a similar PR merged into the 0.10.9 branch which has since been merged into master.  I haven't checked out the 0.11.0 branch yet to see if it has significant work that we will want to merge into master.

Before moving to this fork, this repo used a lot of long-lived bug-fix and feature branches.  I'm starting to think we would be better off avoiding long lived branches and just have PRs go towards master.  Would we be able to re-open the PR against the master branch, so double check that a similar fix hasn't already been implemented there?

**Comment by Moreno97** [comment]
Yes, it's merged now. But if you see the commit, the changes are very similar with my changes, although my commit on the other repo is older (source code copied?).
https://github.com/joltup/rn-fetch-blob/commit/a88b59f0e9f62330a5f2a5a7921b6869ba7228b3

**Comment by Traviskn** [comment]
It's possible the code was copied from the other repo by the contributor - sorry about that! In any case this issue should now be fixed.  Thanks for your contributions!

**Pull request closed without merging**
