### PR TITLE
Fix #35

### LINKED ISSUE #35: Invoke would be called more than once during cp call
RNFetchBlob version: 0.10.8
The code raises a java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code. when cp errors but successfully closes its streams.
That is already existed in the old repository and had a PR: [https://github.com/wkh237/react-native-fetch-blob/pull/408](https://github.com/wkh237/react-native-fetch-blob/pull/408)
But now it is still here.

### PR DESCRIPTION
**Pull request by padampadam**
this should fix #35. It is basically this [wkh237#408](https://github.com/wkh237/react-native-fetch-blob/pull/408)

### CODE REVIEW

**Comment by johanpoirier** [comment]
Why this PR has been closed?

**Comment by johanpoirier** [comment]
I will test it.

**Comment by fiznool** [comment]
Seeing this error too, would be great to get this re-opened and merged in.

**Comment by padampadam** [comment]
@fiznool i was waiting for @johanpoirier to test this out, as i'm actually not to sure this fix is actually working. if you would like to test this out, i would happily reopen this PR.

**Comment by fiznool** [comment]
@padampadam thanks, I opened a new one anyway at #149

**Pull request closed without merging**
